import { LegalPage } from '@/components/LegalPage'

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" effectiveDate="January 1, 2025">
      <p>
        This Privacy Policy describes how OM.Network LLC (&quot;EventDBX,&quot;
        &quot;we,&quot; or &quot;us&quot;) collects, uses, and safeguards
        personal information when you use our managed data hosting services,
        interact with our websites and support channels, or otherwise engage our
        offerings. Our platform is a fully managed environment for storing,
        replicating, and serving customer data (the &quot;EventDBX
        platform&quot;), and we treat the security of that data as a core
        product feature.
      </p>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          1. Scope and definitions
        </h2>
        <p>
          This policy applies to information we process about administrators,
          end users, and visitors (collectively, &quot;users&quot;) in
          connection with the EventDBX platform. Customer-controlled datasets
          stored in your projects remain your property, and we act as a
          processor for that content.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          2. Information we collect
        </h2>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>
            <strong>Account details.</strong> Names, email addresses,
            authentication identifiers, billing contacts, and organization
            metadata you provide when creating or managing an account.
          </li>
          <li>
            <strong>Service data.</strong> Databases, files, and structured
            objects you store on the EventDBX platform, along with schema
            definitions, access controls, and audit logs generated by your
            usage.
          </li>
          <li>
            <strong>Usage analytics.</strong> IP addresses, device details,
            feature interactions, and performance telemetry that help us monitor
            capacity, prevent abuse, and improve reliability.
          </li>
          <li>
            <strong>Support interactions.</strong> Tickets, screenshots, log
            snippets, or diagnostic bundles you voluntarily share when
            requesting assistance.
          </li>
          <li>
            <strong>Marketing preferences.</strong> Content choices you make
            when subscribing to product updates or events.
          </li>
        </ul>
        <p>
          We do not sell personal information and only access service data as
          needed to operate and secure the platform or when you ask us to help.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          3. How we use information
        </h2>
        <p>
          We process information solely to deliver and protect the EventDBX
          platform:
        </p>
        <ol className="list-decimal space-y-1 pl-6 text-gray-300">
          <li>Provisioning projects, storage, networking, and backups.</li>
          <li>
            Monitoring performance, preventing fraud, and enforcing acceptable
            use policies.
          </li>
          <li>
            Providing customer support, training, and incident notifications.
          </li>
          <li>
            Sending service communications, release notes, and security
            advisories.
          </li>
          <li>
            Meeting legal obligations and responding to lawful disclosure
            requests.
          </li>
        </ol>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          4. Sharing and processors
        </h2>
        <p>
          EventDBX uses carefully vetted subprocessors (such as hosting
          providers, observability tools, and payment vendors) to operate the
          EventDBX platform. Each provider must comply with confidentiality
          obligations and security controls consistent with this policy. We may
          also share limited personal data:
        </p>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>When you install marketplace integrations or APIs you direct.</li>
          <li>
            To comply with applicable law, court orders, or defend legal claims.
          </li>
          <li>
            In connection with a merger, acquisition, or financing, provided the
            recipient honors this policy.
          </li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          5. Data retention and deletion
        </h2>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>
            Account records remain active for the life of the subscription and
            up to 120 days after termination, unless you request earlier
            removal.
          </li>
          <li>
            Service data persists according to the retention policies configured
            inside your projects; you control when to delete datasets,
            snapshots, and replicas.
          </li>
          <li>
            System logs and encrypted backups are cycled on a rolling 35-day
            schedule, except where law or incident investigations require longer
            retention.
          </li>
        </ul>
        <p>
          Deletion requests can be submitted via privacy@eventdbx.com or the
          EventDBX console. We will confirm completion when legally permitted.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          6. Security practices
        </h2>
        <p>
          The EventDBX platform encrypts data at rest and in transit, enforces
          multi-factor authentication for privileged access, isolates production
          networks, and runs third-party penetration tests at least annually.
          Access to customer content is limited to trained personnel under
          strict logging and just-in-time authorization.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          7. Your rights and choices
        </h2>
        <p>
          Depending on your region, you may have the right to access, rectify,
          export, object to, or delete personal information. We honor requests
          submitted through the channels below and will verify identity before
          fulfilling them.
        </p>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>
            <strong>Email:</strong> privacy@eventdbx.com
          </li>
          <li>
            <strong>Console:</strong> Settings → Privacy inside the EventDBX
            dashboard.
          </li>
          <li>
            <strong>Marketing opt-out:</strong> Click the unsubscribe link in
            any non-transactional email.
          </li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          8. International data transfers
        </h2>
        <p>
          EventDBX is headquartered in the United States and may process data in
          other countries where we or our subprocessors operate. When
          transferring personal information across borders we rely on Standard
          Contractual Clauses or other lawful safeguards and maintain technical
          controls to keep your data protected.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">9. Updates</h2>
        <p>
          We will update this policy when regulations, security practices, or
          product capabilities change. Material updates will be announced via
          email and in-product notices at least 30 days before they take effect.
          Continued use of the EventDBX platform after the effective date
          constitutes acceptance of the revised policy.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">10. Contact</h2>
        <p>
          Questions about this policy or our privacy program? Email{' '}
          <strong>privacy@eventdbx.com</strong> or write to OM.Network, LLC dba
          EventDBX, 5428 S Regal St, Spokane, WA 99223-9998, USA.
        </p>
      </section>
    </LegalPage>
  )
}
